name: Check Rebuild Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bash-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SQLite
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3
        sqlite3 --version

    - name: Make script executable
      run: chmod +x ./rebuild_database.sh

    - name: Create database
      run: touch ./database/mot_garage_db.sqlite

    - name: Run Bash script & Check output
      run: |
        OUTPUT=$(./rebuild_database.sh)
        echo "$OUTPUT"
        if echo "$OUTPUT" | grep -i -q "error"; then
          echo "Error when rebuilding database"
          exit 1
        else
          echo "No errors when rebuilding database"
        fi
